"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import { setupStore } from "@/store/store";
import { AppBar, Container, Toolbar, Typography } from "@mui/material";
import LoginIcon from "@mui/icons-material/Login";
import { Box } from "@mui/material";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const store = setupStore();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider store={store}>
          <AppBar
            position="sticky"
            className="flex flex-row flex-nowrap"
            sx={{
              display: "flex",
              flexDirection: "row",
              justifyContent: "space-between",
              alignItems: "center",
              padding: "8px",
            }}
          >
            <Typography variant="h6">СТРОЙСНАБЖЕНИЕ</Typography>
            <Link href="/products">К списку продукции</Link>
            <Link href="/logout">Выйти</Link>
            <Link href="/login">Войти</Link>
            <Link href="/register">Зарегистрироваться</Link>
            <LoginIcon fontSize="large" />
          </AppBar>
          {children}
        </Provider>
      </body>
    </html>
  );
}
